# Generated by Django 2.2.7 on 2020-02-16 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etna_app', '0002_elaqe_melumatlari_elaqe_sekil_haqqimizda_melumatlari_haqqimizda_sekil_xidmetler_sekil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Haqqimizda_basliq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Haqqimizda_sonluq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer', models.TextField()),
            ],
        ),
    ]
