# Generated by Django 2.2.7 on 2020-02-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etna_app', '0003_haqqimizda_basliq_haqqimizda_sonluq'),
    ]

    operations = [
        migrations.AddField(
            model_name='haqqimizda_basliq',
            name='header_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='haqqimizda_basliq',
            name='header_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='haqqimizda_basliq',
            name='header_ru',
            field=models.TextField(null=True),
        ),
    ]
