# Generated by Django 2.2.7 on 2020-02-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etna_app', '0004_auto_20200218_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='haqqimizda_melumatlari',
            name='sadalanan_melumatlar_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='haqqimizda_melumatlari',
            name='sadalanan_melumatlar_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='haqqimizda_melumatlari',
            name='sadalanan_melumatlar_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='haqqimizda_sonluq',
            name='footer_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='haqqimizda_sonluq',
            name='footer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='haqqimizda_sonluq',
            name='footer_ru',
            field=models.TextField(null=True),
        ),
    ]
