# Generated by Django 2.2.7 on 2020-02-18 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etna_app', '0005_auto_20200218_1701'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Haqqimizda_sonluq',
        ),
    ]
